# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@15.2.10
    npm install
    npm run build
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    api_location: ''
    output_location: 'dist/d1-biz'
    azure_static_web_apps_api_token: "a4f523c4a6900f5d0f98c0243e305c833c8e28378e9b1745549449595441a0d55-e96f017a-edb1-423a-a4e0-29bc648cb02b003424417"
  displayName: 'Deploy to Azure Static Web Apps'
  
